--------------------------------------------------------
-- Archivo creado  - lunes-abril-24-2023
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "CLIENTE"
   (	"NIT" NUMBER(*,0),
	"CNOMBRE" VARCHAR2(30 BYTE),
	"CAPELLIDO" VARCHAR2(30 BYTE),
	"CTELEFONO" VARCHAR2(15 BYTE),
	"CEMAIL" VARCHAR2(50 BYTE),
	"CDIRECCION" VARCHAR2(65 BYTE),
	"NUM_SERVICIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMPRAS
--------------------------------------------------------

  CREATE TABLE "COMPRAS"
   (	"ID_COMPRAS" NUMBER(*,0),
	"NOMBRE_CO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MECANICO
--------------------------------------------------------

  CREATE TABLE "MECANICO"
   (	"ID_MEC" NUMBER(*,0),
	"MNOMBRE" VARCHAR2(50 BYTE),
	"DISPONIBILIDAD" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTIFICACIONES
--------------------------------------------------------

  CREATE TABLE "NOTIFICACIONES"
   (	"ID_NOTI" NUMBER(*,0),
	"NOMBRE_N" VARCHAR2(50 BYTE),
	"CORREO_N" VARCHAR2(100 BYTE),
	"DESCRIPCION_N" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table RECIBO
--------------------------------------------------------

  CREATE TABLE "RECIBO"
   (	"ID_RECIBO" NUMBER(*,0),
	"SERV_MEC_ID" NUMBER(*,0),
	"OBSERVACION" VARCHAR2(100 BYTE),
	"DESCUENTO" NUMBER(10,2),
	"COSTO_TOTAL" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REPUESTO
--------------------------------------------------------

  CREATE TABLE "REPUESTO"
   (	"ID_REPUESTO" NUMBER(*,0),
	"RNOMBRE" VARCHAR2(50 BYTE),
	"RCANTIDAD" NUMBER(*,0),
	"RPRECIO" NUMBER(10,2),
	"STOCK_MIN" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "ROL"
   (	"ID_ROL" NUMBER(*,0),
	"DESCRIPCION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVICIO
--------------------------------------------------------

  CREATE TABLE "SERVICIO"
   (	"ID_SERVICIO" NUMBER(*,0),
	"SNOMBRE" VARCHAR2(50 BYTE),
	"SCOSTO" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVICIO_MECANICO
--------------------------------------------------------

  CREATE TABLE "SERVICIO_MECANICO"
   (	"ID_SERV_MEC" NUMBER(*,0),
	"SERVICIO_ID" NUMBER(*,0),
	"REPUESTO_ID" NUMBER(*,0),
	"MECANICO_ID" NUMBER(*,0),
	"CLIENTE_NIT" NUMBER(*,0),
	"VEHICULO_PLACA" VARCHAR2(7 BYTE),
	"FECHA" DATE,
	"ESTADO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRABAJADOR
--------------------------------------------------------

  CREATE TABLE "TRABAJADOR"
   (	"TNUM" NUMBER(*,0),
	"CONTRASENIA" VARCHAR2(10 BYTE),
	"TNOMBRE" VARCHAR2(30 BYTE),
	"TAPELLIDO" VARCHAR2(30 BYTE),
	"ROL_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VEHICULO
--------------------------------------------------------

  CREATE TABLE "VEHICULO"
   (	"PLACA" VARCHAR2(7 BYTE),
	"MARCA" VARCHAR2(20 BYTE),
	"LINEA" VARCHAR2(20 BYTE),
	"MODELO" NUMBER(*,0),
	"NIT_CLIENTE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008469
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008469" ON "CLIENTE" ("NIT")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008507
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008507" ON "COMPRAS" ("ID_COMPRAS")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index SYS_C008480
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008480" ON "MECANICO" ("ID_MEC")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index SYS_C008505
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008505" ON "NOTIFICACIONES" ("ID_NOTI")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index SYS_C008500
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008500" ON "RECIBO" ("ID_RECIBO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008457
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008457" ON "REPUESTO" ("ID_REPUESTO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008444
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008444" ON "ROL" ("ID_ROL")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008461
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008461" ON "SERVICIO" ("ID_SERVICIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008489
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008489" ON "SERVICIO_MECANICO" ("ID_SERV_MEC")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008450
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008450" ON "TRABAJADOR" ("TNUM")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008475
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008475" ON "VEHICULO" ("PLACA")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger AUMENTAR_NUM_SERVICIO_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUMENTAR_NUM_SERVICIO_TRIGGER"
AFTER INSERT ON RECIBO
FOR EACH ROW
BEGIN
    DECLARE
        cliente_nit_in INTEGER;
    BEGIN
        SELECT cliente_nit INTO cliente_nit_in FROM SERVICIO_MECANICO WHERE id_serv_mec = :NEW.serv_mec_id;
        aumentar_num_servicio(cliente_nit_in);
END;
END;
/
ALTER TRIGGER "AUMENTAR_NUM_SERVICIO_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTOINCREMENT_ID_MEC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUTOINCREMENT_ID_MEC"
    BEFORE INSERT ON MECANICO
    FOR EACH ROW
    BEGIN
        SELECT COALESCE(MAX(id_mec), 0) + 1 INTO :new.id_mec FROM MECANICO;
    END;
/
ALTER TRIGGER "AUTOINCREMENT_ID_MEC" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTOINCREMENT_ID_RECIBO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUTOINCREMENT_ID_RECIBO"
    BEFORE INSERT ON RECIBO
    FOR EACH ROW
    BEGIN
        SELECT COALESCE(MAX(id_recibo), 0) + 1 INTO :new.id_recibo FROM RECIBO;
    END;
/
ALTER TRIGGER "AUTOINCREMENT_ID_RECIBO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTOINCREMENT_ID_REPUESTO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUTOINCREMENT_ID_REPUESTO"
    BEFORE INSERT ON REPUESTO
    FOR EACH ROW
    BEGIN
        SELECT COALESCE(MAX(id_repuesto), 0) + 1 INTO :new.id_repuesto FROM REPUESTO;
    END;
/
ALTER TRIGGER "AUTOINCREMENT_ID_REPUESTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTOINCREMENT_ID_ROL
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUTOINCREMENT_ID_ROL"
    BEFORE INSERT ON ROL
    FOR EACH ROW
    BEGIN
        SELECT COALESCE(MAX(id_rol), 0) + 1 INTO :new.id_rol FROM ROL;
    END;
/
ALTER TRIGGER "AUTOINCREMENT_ID_ROL" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTOINCREMENT_ID_SERVICIO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUTOINCREMENT_ID_SERVICIO"
    BEFORE INSERT ON SERVICIO
    FOR EACH ROW
    BEGIN
        SELECT COALESCE(MAX(id_servicio), 0) + 1 INTO :new.id_servicio FROM SERVICIO;
    END;
/
ALTER TRIGGER "AUTOINCREMENT_ID_SERVICIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTOINCREMENT_ID_SERV_MEC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUTOINCREMENT_ID_SERV_MEC"
    BEFORE INSERT ON SERVICIO_MECANICO
    FOR EACH ROW
    BEGIN
        SELECT COALESCE(MAX(id_serv_mec), 0) + 1 INTO :new.id_serv_mec FROM SERVICIO_MECANICO;
    END;
/
ALTER TRIGGER "AUTOINCREMENT_ID_SERV_MEC" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTOINCREMENT_TNUM
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUTOINCREMENT_TNUM"
    BEFORE INSERT ON TRABAJADOR
    FOR EACH ROW
    BEGIN
        SELECT COALESCE(MAX(tnum), 22000) + 1 INTO :new.tnum FROM TRABAJADOR;
    END;
/
ALTER TRIGGER "AUTOINCREMENT_TNUM" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DESCUENTO_RECIBO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "DESCUENTO_RECIBO"
AFTER INSERT OR UPDATE OF num_servicio ON CLIENTE
FOR EACH ROW
DECLARE
    v_num_servicio NUMBER;
BEGIN
    v_num_servicio := :NEW.num_servicio;
    IF MOD(v_num_servicio, 5) = 0 THEN
        INSERT INTO Recibo (descuento)
        VALUES ('10%');
    END IF;
END;
/
ALTER TRIGGER "DESCUENTO_RECIBO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REGISTRAR_MECANICO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "REGISTRAR_MECANICO"
AFTER INSERT ON TRABAJADOR
FOR EACH ROW
BEGIN
    IF :NEW.rol_id = 2 THEN
        INSERT INTO MECANICO (id_mec, mnombre, disponibilidad)
        VALUES (NULL, :NEW.tnombre || ' ' || :NEW.tapellido, 1);
    END IF;
END;
/
ALTER TRIGGER "REGISTRAR_MECANICO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SERVICIO_MECANICO_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SERVICIO_MECANICO_TRIGGER"
AFTER UPDATE ON SERVICIO_MECANICO
FOR EACH ROW
 WHEN (NEW.estado = 1) BEGIN
    DECLARE
        v_cliente_nombre VARCHAR(50);
        v_cliente_correo VARCHAR(100);
    BEGIN
        SELECT cnombre, cemail
        INTO v_cliente_nombre, v_cliente_correo
        FROM CLIENTE
        WHERE nit = :NEW.cliente_nit;

        INSERT INTO notificaciones (id_noti, nombre_n, correo_n, descripcion_n)
        VALUES (NULL, v_cliente_nombre, v_cliente_correo, 'Su servicio ha sido finalizado');
    END;
END;
/
ALTER TRIGGER "SERVICIO_MECANICO_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STOCK_MINIMO_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "STOCK_MINIMO_TRIGGER"
AFTER UPDATE ON REPUESTO
FOR EACH ROW
 WHEN (NEW.rcantidad <= NEW.stock_min) BEGIN
    INSERT INTO COMPRAS (id_compras, nombre_co)
    VALUES (NULL, :NEW.RNOMBRE);
END;
/
ALTER TRIGGER "STOCK_MINIMO_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DESCUENTO_RECIBO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "DESCUENTO_RECIBO"
AFTER INSERT OR UPDATE OF num_servicio ON CLIENTE
FOR EACH ROW
DECLARE
    v_num_servicio NUMBER;
BEGIN
    v_num_servicio := :NEW.num_servicio;
    IF MOD(v_num_servicio, 5) = 0 THEN
        INSERT INTO Recibo (descuento)
        VALUES ('10%');
    END IF;
END;
/
ALTER TRIGGER "DESCUENTO_RECIBO" ENABLE;

--------------------------------------------------------
--  DDL for Trigger AUTOINCREMENT_ID_MEC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUTOINCREMENT_ID_MEC"
    BEFORE INSERT ON MECANICO
    FOR EACH ROW
    BEGIN
        SELECT COALESCE(MAX(id_mec), 0) + 1 INTO :new.id_mec FROM MECANICO;
    END;
/
ALTER TRIGGER "AUTOINCREMENT_ID_MEC" ENABLE;

--------------------------------------------------------
--  DDL for Trigger AUTOINCREMENT_ID_RECIBO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUTOINCREMENT_ID_RECIBO"
    BEFORE INSERT ON RECIBO
    FOR EACH ROW
    BEGIN
        SELECT COALESCE(MAX(id_recibo), 0) + 1 INTO :new.id_recibo FROM RECIBO;
    END;
/
ALTER TRIGGER "AUTOINCREMENT_ID_RECIBO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTOINCREMENT_ID_REPUESTO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUTOINCREMENT_ID_REPUESTO"
    BEFORE INSERT ON REPUESTO
    FOR EACH ROW
    BEGIN
        SELECT COALESCE(MAX(id_repuesto), 0) + 1 INTO :new.id_repuesto FROM REPUESTO;
    END;
/
ALTER TRIGGER "AUTOINCREMENT_ID_REPUESTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STOCK_MINIMO_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "STOCK_MINIMO_TRIGGER"
AFTER UPDATE ON REPUESTO
FOR EACH ROW
 WHEN (NEW.rcantidad <= NEW.stock_min) BEGIN
    INSERT INTO COMPRAS (id_compras, nombre_co)
    VALUES (NULL, :NEW.RNOMBRE);
END;
/
ALTER TRIGGER "STOCK_MINIMO_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTOINCREMENT_ID_ROL
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUTOINCREMENT_ID_ROL"
    BEFORE INSERT ON ROL
    FOR EACH ROW
    BEGIN
        SELECT COALESCE(MAX(id_rol), 0) + 1 INTO :new.id_rol FROM ROL;
    END;
/
ALTER TRIGGER "AUTOINCREMENT_ID_ROL" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTOINCREMENT_ID_SERVICIO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUTOINCREMENT_ID_SERVICIO"
    BEFORE INSERT ON SERVICIO
    FOR EACH ROW
    BEGIN
        SELECT COALESCE(MAX(id_servicio), 0) + 1 INTO :new.id_servicio FROM SERVICIO;
    END;
/
ALTER TRIGGER "AUTOINCREMENT_ID_SERVICIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTOINCREMENT_ID_SERV_MEC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUTOINCREMENT_ID_SERV_MEC"
    BEFORE INSERT ON SERVICIO_MECANICO
    FOR EACH ROW
    BEGIN
        SELECT COALESCE(MAX(id_serv_mec), 0) + 1 INTO :new.id_serv_mec FROM SERVICIO_MECANICO;
    END;
/
ALTER TRIGGER "AUTOINCREMENT_ID_SERV_MEC" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SERVICIO_MECANICO_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SERVICIO_MECANICO_TRIGGER"
AFTER UPDATE ON SERVICIO_MECANICO
FOR EACH ROW
 WHEN (NEW.estado = 1) BEGIN
    DECLARE
        v_cliente_nombre VARCHAR(50);
        v_cliente_correo VARCHAR(100);
    BEGIN
        SELECT cnombre, cemail
        INTO v_cliente_nombre, v_cliente_correo
        FROM CLIENTE
        WHERE nit = :NEW.cliente_nit;

        INSERT INTO notificaciones (id_noti, nombre_n, correo_n, descripcion_n)
        VALUES (NULL, v_cliente_nombre, v_cliente_correo, 'Su servicio ha sido finalizado');
    END;
END;
/
ALTER TRIGGER "SERVICIO_MECANICO_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTOINCREMENT_TNUM
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUTOINCREMENT_TNUM"
    BEFORE INSERT ON TRABAJADOR
    FOR EACH ROW
    BEGIN
        SELECT COALESCE(MAX(tnum), 22000) + 1 INTO :new.tnum FROM TRABAJADOR;
    END;
/
ALTER TRIGGER "AUTOINCREMENT_TNUM" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REGISTRAR_MECANICO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "REGISTRAR_MECANICO"
AFTER INSERT ON TRABAJADOR
FOR EACH ROW
BEGIN
    IF :NEW.rol_id = 2 THEN
        INSERT INTO MECANICO (id_mec, mnombre, disponibilidad)
        VALUES (NULL, :NEW.tnombre || ' ' || :NEW.tapellido, 1);
    END IF;
END;
/
ALTER TRIGGER "REGISTRAR_MECANICO" ENABLE;
--------------------------------------------------------
--  DDL for Procedure AUMENTAR_NUM_SERVICIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "AUMENTAR_NUM_SERVICIO" (cliente_nit_in IN INTEGER)
AS
BEGIN
    UPDATE CLIENTE SET num_servicio = num_servicio + 1 WHERE nit = cliente_nit_in;
END;

/
--------------------------------------------------------
--  DDL for Trigger AUMENTAR_NUM_SERVICIO_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUMENTAR_NUM_SERVICIO_TRIGGER"
AFTER INSERT ON RECIBO
FOR EACH ROW
BEGIN
    DECLARE
        cliente_nit_in INTEGER;
    BEGIN
        SELECT cliente_nit INTO cliente_nit_in FROM SERVICIO_MECANICO WHERE id_serv_mec = :NEW.serv_mec_id;
        aumentar_num_servicio(cliente_nit_in);
END;
END;
/
ALTER TRIGGER "AUMENTAR_NUM_SERVICIO_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_REPUESTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ELIMINAR_REPUESTO"
IS
BEGIN
    DELETE FROM compras WHERE nombre_co IN (
        SELECT rnombre FROM repuesto WHERE rcantidad > stock_min
    );
    COMMIT; -- opcional, para confirmar delete de datos
END eliminar_repuesto;

/
--------------------------------------------------------
--  DDL for Trigger AUTOINCREMENT_ID_COMPRAS
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUTOINCREMENT_ID_COMPRAS"
    BEFORE INSERT ON COMPRAS
    FOR EACH ROW
    BEGIN
        SELECT COALESCE(MAX(id_compras), 0) + 1 INTO :new.id_compras FROM COMPRAS;
    END;
/
--------------------------------------------------------
--  DDL for Trigger AUTOINCREMENT_ID_NOTIFICACION
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUTOINCREMENT_ID_NOTIFICACION"
BEFORE INSERT ON notificaciones
FOR EACH ROW
BEGIN
    SELECT COALESCE(MAX(id_noti), 0) + 1 INTO :new.id_noti FROM notificaciones;
END;
/
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "CLIENTE" MODIFY ("NIT" NOT NULL ENABLE);
  ALTER TABLE "CLIENTE" MODIFY ("CNOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CLIENTE" MODIFY ("CAPELLIDO" NOT NULL ENABLE);
  ALTER TABLE "CLIENTE" MODIFY ("CTELEFONO" NOT NULL ENABLE);
  ALTER TABLE "CLIENTE" MODIFY ("CEMAIL" NOT NULL ENABLE);
  ALTER TABLE "CLIENTE" MODIFY ("CDIRECCION" NOT NULL ENABLE);
  ALTER TABLE "CLIENTE" MODIFY ("NUM_SERVICIO" NOT NULL ENABLE);
  ALTER TABLE "CLIENTE" ADD PRIMARY KEY ("NIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPRAS
--------------------------------------------------------

  ALTER TABLE "COMPRAS" MODIFY ("NOMBRE_CO" NOT NULL ENABLE);
  ALTER TABLE "COMPRAS" ADD PRIMARY KEY ("ID_COMPRAS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;

--------------------------------------------------------
--  Constraints for Table MECANICO
--------------------------------------------------------

  ALTER TABLE "MECANICO" MODIFY ("ID_MEC" NOT NULL ENABLE);
  ALTER TABLE "MECANICO" MODIFY ("MNOMBRE" NOT NULL ENABLE);
  ALTER TABLE "MECANICO" MODIFY ("DISPONIBILIDAD" NOT NULL ENABLE);
  ALTER TABLE "MECANICO" ADD PRIMARY KEY ("ID_MEC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

--------------------------------------------------------
--  Constraints for Table NOTIFICACIONES
--------------------------------------------------------

  ALTER TABLE "NOTIFICACIONES" MODIFY ("NOMBRE_N" NOT NULL ENABLE);
  ALTER TABLE "NOTIFICACIONES" MODIFY ("CORREO_N" NOT NULL ENABLE);
  ALTER TABLE "NOTIFICACIONES" MODIFY ("DESCRIPCION_N" NOT NULL ENABLE);
  ALTER TABLE "NOTIFICACIONES" ADD PRIMARY KEY ("ID_NOTI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RECIBO
--------------------------------------------------------

  ALTER TABLE "RECIBO" MODIFY ("ID_RECIBO" NOT NULL ENABLE);
  ALTER TABLE "RECIBO" MODIFY ("SERV_MEC_ID" NOT NULL ENABLE);
  ALTER TABLE "RECIBO" MODIFY ("OBSERVACION" NOT NULL ENABLE);
  ALTER TABLE "RECIBO" MODIFY ("DESCUENTO" NOT NULL ENABLE);
  ALTER TABLE "RECIBO" MODIFY ("COSTO_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "RECIBO" ADD PRIMARY KEY ("ID_RECIBO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPUESTO
--------------------------------------------------------

  ALTER TABLE "REPUESTO" MODIFY ("ID_REPUESTO" NOT NULL ENABLE);
  ALTER TABLE "REPUESTO" MODIFY ("RNOMBRE" NOT NULL ENABLE);
  ALTER TABLE "REPUESTO" MODIFY ("RCANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "REPUESTO" MODIFY ("RPRECIO" NOT NULL ENABLE);
  ALTER TABLE "REPUESTO" MODIFY ("STOCK_MIN" NOT NULL ENABLE);
  ALTER TABLE "REPUESTO" ADD PRIMARY KEY ("ID_REPUESTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "ROL" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ROL" ADD PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICIO
--------------------------------------------------------

  ALTER TABLE "SERVICIO" MODIFY ("ID_SERVICIO" NOT NULL ENABLE);
  ALTER TABLE "SERVICIO" MODIFY ("SNOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SERVICIO" MODIFY ("SCOSTO" NOT NULL ENABLE);
  ALTER TABLE "SERVICIO" ADD PRIMARY KEY ("ID_SERVICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICIO_MECANICO
--------------------------------------------------------

  ALTER TABLE "SERVICIO_MECANICO" MODIFY ("ID_SERV_MEC" NOT NULL ENABLE);
  ALTER TABLE "SERVICIO_MECANICO" MODIFY ("SERVICIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SERVICIO_MECANICO" MODIFY ("REPUESTO_ID" NOT NULL ENABLE);
  ALTER TABLE "SERVICIO_MECANICO" MODIFY ("MECANICO_ID" NOT NULL ENABLE);
  ALTER TABLE "SERVICIO_MECANICO" MODIFY ("CLIENTE_NIT" NOT NULL ENABLE);
  ALTER TABLE "SERVICIO_MECANICO" MODIFY ("VEHICULO_PLACA" NOT NULL ENABLE);
  ALTER TABLE "SERVICIO_MECANICO" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "SERVICIO_MECANICO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SERVICIO_MECANICO" ADD PRIMARY KEY ("ID_SERV_MEC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRABAJADOR
--------------------------------------------------------

  ALTER TABLE "TRABAJADOR" MODIFY ("TNUM" NOT NULL ENABLE);
  ALTER TABLE "TRABAJADOR" MODIFY ("CONTRASENIA" NOT NULL ENABLE);
  ALTER TABLE "TRABAJADOR" MODIFY ("TNOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TRABAJADOR" MODIFY ("TAPELLIDO" NOT NULL ENABLE);
  ALTER TABLE "TRABAJADOR" MODIFY ("ROL_ID" NOT NULL ENABLE);
  ALTER TABLE "TRABAJADOR" ADD PRIMARY KEY ("TNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VEHICULO
--------------------------------------------------------

  ALTER TABLE "VEHICULO" MODIFY ("PLACA" NOT NULL ENABLE);
  ALTER TABLE "VEHICULO" MODIFY ("MARCA" NOT NULL ENABLE);
  ALTER TABLE "VEHICULO" MODIFY ("LINEA" NOT NULL ENABLE);
  ALTER TABLE "VEHICULO" MODIFY ("MODELO" NOT NULL ENABLE);
  ALTER TABLE "VEHICULO" MODIFY ("NIT_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "VEHICULO" ADD PRIMARY KEY ("PLACA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECIBO
--------------------------------------------------------

  ALTER TABLE "RECIBO" ADD FOREIGN KEY ("SERV_MEC_ID")
	  REFERENCES "SERVICIO_MECANICO" ("ID_SERV_MEC") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICIO_MECANICO
--------------------------------------------------------

  ALTER TABLE "SERVICIO_MECANICO" ADD FOREIGN KEY ("SERVICIO_ID")
	  REFERENCES "SERVICIO" ("ID_SERVICIO") ENABLE;
  ALTER TABLE "SERVICIO_MECANICO" ADD FOREIGN KEY ("REPUESTO_ID")
	  REFERENCES "REPUESTO" ("ID_REPUESTO") ENABLE;
  ALTER TABLE "SERVICIO_MECANICO" ADD FOREIGN KEY ("MECANICO_ID")
	  REFERENCES "MECANICO" ("ID_MEC") ENABLE;
  ALTER TABLE "SERVICIO_MECANICO" ADD FOREIGN KEY ("CLIENTE_NIT")
	  REFERENCES "CLIENTE" ("NIT") ENABLE;
  ALTER TABLE "SERVICIO_MECANICO" ADD FOREIGN KEY ("VEHICULO_PLACA")
	  REFERENCES "VEHICULO" ("PLACA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRABAJADOR
--------------------------------------------------------

  ALTER TABLE "TRABAJADOR" ADD FOREIGN KEY ("ROL_ID")
	  REFERENCES "ROL" ("ID_ROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VEHICULO
--------------------------------------------------------

  ALTER TABLE "VEHICULO" ADD FOREIGN KEY ("NIT_CLIENTE")
	  REFERENCES "CLIENTE" ("NIT") ENABLE;
